import tornado.escape
import tornado.web
from .db import create_tables, database

create_tables()


class MainHandler(tornado.web.RequestHandler):

    def prepare(self):
        self.xsrf_token
        if not database.is_closed():
            database.close()
        database.connect()
        return super().prepare()

    def on_finish(self):
        if not database.is_closed():
            database.close()
        return super().on_finish()

    def get(self):
        self.write(dict(msg="Generated by Emacs"))
