#!/bin/sh
### BEGIN INIT INFO
# Provides:           shadowsocks
# Required-Start:     $local_fs $network $named $time $syslog
# Required-Stop:      $local_fs $network $named $time $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Description:        This is the System V style init script for shadowsocks
### END INIT INFO

NAME=shadowsocks
BIN=/usr/local/bin/sslocal
if [ -f /etc/shadowsocks.json ]; then # -f file -> True is file exists and is a a regualr file
    CONF=/etc/shadowsocks.json
else
    echo "Please write your configuration file -- /etc/shadowsocks.json"
    exit 1
fi
RETVAL=0

check_running(){
    PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
    if [ ! -z $PID ]; then # -z string -> True if the length of string is zero
	return 0
    else
	return 1
    fi
}

do_start(){
    check_running
    if [ $? -eq 0 ]; then
	echo "$NAME (pid $PID) is already running..."
	exit 0
    else
	$BIN -c $CONF -d start
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
	    echo "Starting $NAME success"
	else
	    echo "Starting $NAME failed"
	fi
    fi
}

do_stop(){
    check_running
    if [ $? -eq 0 ]; then
	$BIN -c $CONF -d stop
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
	    echo "Stopping $NAME success"
	else
	    echo "Stopping $NAME failed"
	fi
    else
	echo "$NAME is stopped"
	RETVAL=1
    fi
}

do_status(){
    check_running
    if [ $? -eq 0 ]; then
	echo "$NAME (pid $PID) is running..."
    else
	echo "$NAME is stopped"
	RETVAL=1
    fi
}

do_restart(){
    do_stop
    do_start
}

do_uninstall(){
    echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|no]"
    local SURE
    read SURE
    if [ ${SURE} = "yes" ]; then
	do_stop
	update-rc.d -f ${NAME} remove
    fi
}

case "$1" in
    start|stop|restart|status|uninstall)
	do_$1
	;;
    *)
	echo "Usage: $0 { start | stop | restart | status | uninstall }"
	RETVAL=1
esac

exit $RETVAL
