(require-install 'js2-mode)
(require-install 'js2-refactor)
(require-install 'xref-js2)
(require-install 'company)
(require-install 'company-tern)
(require-install 'indium)

(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(add-hook 'js2-mode-hook #'js2-imenu-extras-mode)
(add-hook 'js2-mode-hook #'js2-refactor-mode)
(add-hook 'js2-mode-hook #'indium-interaction-mode)
(js2r-add-keybindings-with-prefix "C-c C-r")
(define-key js-mode-map (kbd "C-k") #'js2r-kill)
(add-hook 'js2-mode-hook #'(lambda ()
			     (add-hook 'xref-backend-functions #'xref-js2-xref-backend nil t)))
(add-to-list 'company-backends 'company-tern)
(add-hook 'js2-mode-hook #'(lambda ()
			     (tern-mode)
			     (company-mode)))
(define-key tern-mode-keymap (kbd "M-.") nil)
(define-key tern-mode-keymap (kbd "M-,") nil)

(require-install 'coffee-mode)
(custom-set-variables '(coffee-indent-like-python-mode t))

(provide 'init-js)
